# Device reading Modbus 6-CH E-Meter WirenBoard WB-MAP6S
# https://wirenboard.com/wiki/WB-MAP6S_Modbus_Power_Meter

substitutions:
  name: e-hub
  friendly_name: Electricity Hub

packages:
  esp32: !include ../esp32/esp32.yaml
  default: !include ../../common/default.yaml
  web: !include ../../common/web.yaml

  map6s: !include
    file: wirenboard/device.yaml
    vars:
      id: map6s
      name: WirenBoard MAP6S
      area_id: electrical_panel
      family_id: map6s
      signature_id: map6sG16
      address: 68
      update_interval: 2s

esphome:
  min_version: 2025.7.0

  project:
    name: "dudanov.e-hub"
    version: "1.0"

  area:
    id: electrical_panel
    name: "Electrical Panel"

  devices:
    - id: ce102m_device
      name: "EnergoMera CE102M"
      area_id: electrical_panel

wifi:
  on_connect:
    then:
      - script.execute: map6s_fetch_fw_version
      - script.execute: map6s_fetch_bootloader_version

time:
  - platform: homeassistant
    on_time:
      # Every 8 hours
      - seconds: 0
        minutes: 0
        hours: /8
        then:
          - script.execute: map6s_fetch_fw_version
          - script.execute: map6s_fetch_bootloader_version

uart:
  baud_rate: 115200
  tx_pin: 18
  rx_pin:
    number: 5
    ignore_strapping_warning: yes

modbus:
  flow_control_pin: 17

sensor:
  # Wattmeter based on the pulse output of an electric meter
  - platform: pulse_meter
    device_id: ce102m_device
    id: sensor_energy_pulse_meter
    name: Power
    device_class: power
    state_class: measurement
    unit_of_measurement: W
    accuracy_decimals: 0
    pin:
      number: 3
      inverted: on
    internal_filter: 100ms
    filters:
      - multiply: 30
    total:
      name: Energy
      device_id: ce102m_device
      id: sensor_total_energy
      unit_of_measurement: kWh
      state_class: total_increasing
      device_class: energy
      accuracy_decimals: 1
      filters:
        - multiply: 5e-4

# Reset total energy button
button:
  - platform: template
    device_id: ce102m_device
    name: Energy Reset
    id: button_reset_total
    on_press:
      - pulse_meter.set_total_pulses:
          id: sensor_energy_pulse_meter
          value: 0

api:
  actions:
    # Action for setting the value of the energy meter
    - action: set_total_energy
      variables:
        kwh: float
      then:
        - pulse_meter.set_total_pulses:
            id: sensor_energy_pulse_meter
            value: !lambda return kwh * 2000;
