http_request:
  verify_ssl: false

script:
  - id: get_${id}_available
    then:
      - http_request.get:
          url: https://fw-releases.wirenboard.com/${id}/by-signature/map6s/main/latest.txt
          capture_response: true
          on_response:
            - text_sensor.template.publish:
                id: ${id}_version_available
                state: !lambda "return body;"

text_sensor:
  - platform: modbus_controller
    id: ${id}_version
    device_id: map6s_device
    modbus_controller_id: map6s
    address: ${address}
    register_type: ${register_type}
    response_size: ${response_size}
    raw_encode: ANSI
    skip_updates: 10
    name: ${name} Version
    icon: mdi:identifier
    entity_category: diagnostic
  - platform: template
    id: ${id}_version_available
    device_id: map6s_device
    name: ${name} Version Available
    update_interval: never
    icon: mdi:identifier
    entity_category: diagnostic

binary_sensor:
  - platform: template
    id: ${id}_update_available
    device_id: map6s_device
    name: ${name} Update
    device_class: update
    entity_category: diagnostic
    lambda: |-
      if (id(${id}_version).state.empty() || id(${id}_version_available).state.empty()) return {};
      return id(${id}_version).state != id(${id}_version_available).state;
