# Service for setting up FollowMe temperature
api:
  actions:
    - action: follow_me
      variables:
        temperature: float
      then:
        midea_ac.follow_me:
          temperature: !lambda "return temperature;"
          beeper: false
