# Works with my LoonaS Curtain Motors
# Needs replace Tuya WBR-3 with ESP-12F

substitutions:
  invert_position: false

esphome:
  project:
    name: "tuya.curtain-motor"
    version: "1.0"

packages:
  esp32: !include ../iot-uni-dongle/device.yaml

tuya:

cover:
  - platform: tuya
    device_class: curtain
    name: None
    control_datapoint: 1
    position_datapoint: 2
    position_report_datapoint: 3
    direction_datapoint: 5
    invert_position: ${invert_position}
