# MAP6S Device Configuration

esphome:
  min_version: 2025.7.0
  devices:
    - id: ${id}_device
      name: ${name}
      area_id: ${area_id}

modbus_controller:
  - id: ${id}_controller
    address: ${address}
    setup_priority: -10
    update_interval: ${update_interval}

packages:
  update: !include
    file: update/${family_id}.yaml
    vars:
      id: ${id}
      signature_id: ${signature_id}

  device: !include
    file: ${family_id}/device.yaml
    vars:
      id: ${id}
