# Default device packages
packages:
  # Minimal config
  minimal: !include minimal.yaml
  # Home Assistant API
  api: !include api.yaml
  # Restart button
  restart: !include buttons/restart.yaml
  # Safe Mode button
  safe-mode: !include buttons/safe-mode.yaml
  # Shutdown button
  #shutdown: !include buttons/shutdown.yaml
  # Uptime text sensor
  uptime: !include sensors/uptime.yaml
  # WiFi Sensors
  wifi: !include sensors/wifi.yaml
