# MAP6S Device Configuration
packages:
  firmware: !include
    file: update_template.yaml
    vars:
      id: fw
      name: Firmware
      address: 250
      register_type: read
      response_size: 32
  bootloader: !include
    file: update_template.yaml
    vars:
      id: bootloader
      name: Bootloader
      address: 330
      register_type: holding
      response_size: 14
  channel1: !include
    file: channel_template.yaml
    vars:
      channel: 1
      current_register: 5146
      power_register: 4870
      factor_register: 4287
      energy_register: 4620
  channel2: !include
    file: channel_template.yaml
    vars:
      channel: 2
      current_register: 5144
      power_register: 4868
      factor_register: 4286
      energy_register: 4616
  channel3: !include
    file: channel_template.yaml
    vars:
      channel: 3
      current_register: 5142
      power_register: 4866
      factor_register: 4285
      energy_register: 4612
  channel4: !include
    file: channel_template.yaml
    vars:
      channel: 4
      current_register: 9242
      power_register: 8966
      factor_register: 8383
      energy_register: 8716
  channel5: !include
    file: channel_template.yaml
    vars:
      channel: 5
      current_register: 9240
      power_register: 8964
      factor_register: 8382
      energy_register: 8712
  channel6: !include
    file: channel_template.yaml
    vars:
      channel: 6
      current_register: 9238
      power_register: 8962
      factor_register: 8381
      energy_register: 8708

modbus_controller:
  - id: map6s
    address: ${address}
    setup_priority: -10
    update_interval: 2s

sensor:
  - platform: modbus_controller
    device_id: map6s_device
    modbus_controller_id: map6s
    address: 4313
    name: Voltage
    state_class: measurement
    device_class: voltage
    unit_of_measurement: V
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    device_id: map6s_device
    modbus_controller_id: map6s
    address: 4344
    name: Frequency
    state_class: measurement
    device_class: frequency
    unit_of_measurement: Hz
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01
