# Config template for firmware update
http_request:
  verify_ssl: false

script:
  - id: get_${id}_available
    then:
      - http_request.get:
          url: https://fw-releases.wirenboard.com/${id}/by-signature/map6s/main/latest.txt
          capture_response: true
          on_response:
            lambda: "id(${id}_version_available).publish_state(body);"

text_sensor:
  - platform: modbus_controller
    id: ${id}_version
    device_id: map6s_device
    modbus_controller_id: map6s
    address: ${address}
    register_type: ${register_type}
    response_size: ${response_size}
    raw_encode: ANSI
    skip_updates: 10
    name: ${name} Version
    icon: mdi:identifier
    entity_category: diagnostic
    on_value:
      lambda: "id(${id}_update_available).publish_state(id(${id}_version_available).state != x);"

  - platform: template
    id: ${id}_version_available
    device_id: map6s_device
    name: ${name} Version Available
    icon: mdi:identifier
    entity_category: diagnostic
    on_value:
      lambda: "id(${id}_update_available).publish_state(id(${id}_version).state != x);"

binary_sensor:
  - platform: template
    id: ${id}_update_available
    device_id: map6s_device
    name: ${name} Update
    device_class: update
    entity_category: diagnostic
