# Config template for a single channel

sensor:
  - platform: modbus_controller
    id: ${id}_current${channel}
    device_id: ${id}_device
    modbus_controller_id: ${id}_controller
    address: ${current_register}
    name: "CH${channel} Current"
    state_class: measurement
    device_class: current
    unit_of_measurement: A
    register_type: read
    value_type: U_DWORD
    accuracy_decimals: 2
    filters:
      - multiply: 2.44141e-7

  - platform: modbus_controller
    id: ${id}_power${channel}
    device_id: ${id}_device
    modbus_controller_id: ${id}_controller
    address: ${power_register}
    name: "CH${channel} Power"
    state_class: measurement
    device_class: power
    unit_of_measurement: W
    register_type: read
    value_type: S_DWORD
    accuracy_decimals: 0
    filters:
      - multiply: 2.44141e-4

  - platform: modbus_controller
    id: ${id}_factor${channel}
    device_id: ${id}_device
    modbus_controller_id: ${id}_controller
    address: ${factor_register}
    name: "CH${channel} Factor"
    state_class: measurement
    device_class: power_factor
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.001

  - platform: modbus_controller
    id: ${id}_energy${channel}
    device_id: ${id}_device
    modbus_controller_id: ${id}_controller
    address: ${energy_register}
    name: "CH${channel} Energy"
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: kWh
    register_type: read
    value_type: U_QWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 1e-5

number:
  # Коэффициент трансформации токового трансформатора
  - platform: modbus_controller
    id: ${id}_turns${channel}
    device_id: ${id}_device
    modbus_controller_id: ${id}_controller
    address: ${turns_register}
    name: "Turns L${channel}"
    register_type: holding
    value_type: U_WORD
    skip_updates: 99
    entity_category: config
    mode: box
    icon: mdi:alpha-k
    unit_of_measurement: K

  # Фазовая задержка токового трансформатора
  - platform: modbus_controller
    id: ${id}_phi${channel}
    device_id: ${id}_device
    modbus_controller_id: ${id}_controller
    address: ${phi_register}
    name: "Phi L${channel}"
    register_type: holding
    value_type: S_WORD
    skip_updates: 99
    entity_category: config
    mode: box
    icon: mdi:delta
    unit_of_measurement: Δ°
