# MAP6S Device Configuration

packages:
  channel1: !include
    file: channel.yaml
    vars:
      device_id: ${device_id}
      channel: 1
      current_register: 5146
      power_register: 4870
      factor_register: 4287
      energy_register: 4620
      # config numbers
      turns_register: 5218
      phi_register: 5221

  channel2: !include
    file: channel.yaml
    vars:
      device_id: ${device_id}
      channel: 2
      current_register: 5144
      power_register: 4868
      factor_register: 4286
      energy_register: 4616
      # config numbers
      turns_register: 5217
      phi_register: 5220

  channel3: !include
    file: channel.yaml
    vars:
      device_id: ${device_id}
      channel: 3
      current_register: 5142
      power_register: 4866
      factor_register: 4285
      energy_register: 4612
      # config numbers
      turns_register: 5216
      phi_register: 5219

  channel4: !include
    file: channel.yaml
    vars:
      device_id: ${device_id}
      channel: 4
      current_register: 9242
      power_register: 8966
      factor_register: 8383
      energy_register: 8716
      # config numbers
      turns_register: 9314
      phi_register: 9317

  channel5: !include
    file: channel.yaml
    vars:
      device_id: ${device_id}
      channel: 5
      current_register: 9240
      power_register: 8964
      factor_register: 8382
      energy_register: 8712
      # config numbers
      turns_register: 9313
      phi_register: 9316

  channel6: !include
    file: channel.yaml
    vars:
      device_id: ${device_id}
      channel: 6
      current_register: 9238
      power_register: 8962
      factor_register: 8381
      energy_register: 8708
      # config numbers
      turns_register: 9312
      phi_register: 9315

sensor:
  - platform: modbus_controller
    device_id: ${device_id}_device
    modbus_controller_id: ${device_id}_controller
    address: 4313
    name: Voltage
    state_class: measurement
    device_class: voltage
    unit_of_measurement: V
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    device_id: ${device_id}_device
    modbus_controller_id: ${device_id}_controller
    address: 4344
    name: Frequency
    state_class: measurement
    device_class: frequency
    unit_of_measurement: Hz
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  # Total sensors

  - platform: combination
    type: sum
    device_id: ${device_id}_device
    name: Total Power
    sources:
      - source: ${device_id}_power1
      - source: ${device_id}_power2
      - source: ${device_id}_power3
      - source: ${device_id}_power4
      - source: ${device_id}_power5
      - source: ${device_id}_power6
  - platform: combination
    type: sum
    device_id: ${device_id}_device
    name: Total Energy
    sources:
      - source: ${device_id}_energy1
      - source: ${device_id}_energy2
      - source: ${device_id}_energy3
      - source: ${device_id}_energy4
      - source: ${device_id}_energy5
      - source: ${device_id}_energy6
