# This light for my project: https://github.com/dudanov/feron-light-advanced-control

substitutions:
  feron: Bedroom

external_components:
  - source: github://dudanov/esphome-components
    components: [feron]
    refresh: 0d

light:
  - platform: feron
    id: feron_light
    name: ${feron} Feron Light
    icon: mdi:ceiling-light

    fade_switch:
      id: feron_fade_switch
      name: ${feron} Feron Light Fade Effect

remote_transmitter:
  id: ir_remote
  pin: 25
  carrier_duty_percent: 100%

#api:
#  services:
#    - service: feron_preset_load
#      # Load specified preset from internal EEPROM
#      variables:
#        preset: int
#      then:
#        - lambda: |-
#            FeronLightOutput::preset_load(id(ir_remote), preset, !id(fade_switch).state);
#    - service: feron_preset_save
#      # Save current state as specified preset to internal EEPROM
#      variables:
#        preset: int
#      then:
#        - lambda: |-
#            FeronLightOutput::preset_save(id(ir_remote), preset);
