substitutions:
  num_leds: "700"

light:
  - platform: neopixelbus
    device_id: led_strip_device
    name: None
    num_leds: ${num_leds}
    power_supply: led_power
    variant: SK6812
    type: GRBW
    pin: 32
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - wled:

wled:

power_supply:
  - id: led_power
    pin: 26
    enable_time: 2s
    keep_on_time: 5s
