substitutions:
  led_id: led
  num_leds: "738"

light:
  - platform: esp32_rmt_led_strip
    device_id: ${led_id}_device
    name: None
    icon: mdi:led-strip-variant
    rgb_order: GRB
    is_rgbw: true
    pin: 32
    num_leds: ${num_leds}
    chipset: SK6812
    use_psram: false
    power_supply: led_power
    effects:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_fireworks:
      - addressable_flicker:
      - wled:

wled:

power_supply:
  - id: led_power
    pin: 26
    enable_time: 2s
    keep_on_time: 5s
