# Single two-buttons switch
# Video: https://youtube.com/shorts/ChQIHIe7WzY

esphome:
  project:
    name: "dudanov.legrand-switch"
    version: "1.0"

packages:
  esp32: !include ../esp32/esp32.yaml
  default: !include ../../common/default.yaml
  web: !include ../../common/web.yaml
  buzzer: !include
    file: ../../common/buzzer/esp32.yaml
    vars:
      pin: 4
  # Two main switch keys
  key1: !include
    file: template.yaml
    vars:
      num: 1
      pin: 0
      ignore_strapping_warning: "yes"
  key2: !include
    file: template.yaml
    vars:
      num: 2
      pin: 33

# Onboard status led
status_led:
  pin: 32
