binary_sensor:
  - platform: gpio
    name: "${friendly_name} Key 5"
    icon: "mdi:electric-switch"
    id: key5
    pin:
      number: GPIO14
      inverted: true
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "${friendly_name} Key 6"
    icon: "mdi:electric-switch"
    id: key6
    pin:
      number: GPIO13
      inverted: true
    filters:
      - delayed_on_off: 50ms
