# Button template for my switch device
# Video: https://youtube.com/shorts/ChQIHIe7WzY

defaults:
  ignore_strapping_warning: "no"

binary_sensor:
  - platform: gpio
    id: key${num}
    pin:
      number: ${pin}
      inverted: yes
      ignore_strapping_warning: ${ignore_strapping_warning}
    filters:
      - delayed_off: 50ms
    on_click:
      then:
        - event.trigger:
            id: event_key${num}
            event_type: click
    on_double_click:
      then:
        - event.trigger:
            id: event_key${num}
            event_type: double_click

event:
  - platform: template
    id: event_key${num}
    name: Event Key ${num}
    # icon: mdi:electric-switch
    device_class: button
    event_types:
      - click
      - double_click
